<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    add product
 
    <form action="" method="post">
        <div>
            <input type="text" name="name" placeholder="name">
            <input type="text" name="price" placeholder="price">
            <input type="submit" name="submit" value="save">
        </div>
    </form>

    <div>

    <?php
    if (isset($message)) {
        echo $message;
    }
    ?>
    </div>
</body>

</html>