<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2>dash</h2>
    <form action="/login/addUser?role=<?php echo $this->request->getQuery('role')?>" method="post">

        <div>
            adduser
            <input type="text" name="name" placeholder="Name">
            <input type="text" name="role" placeholder="role">
            <input type="text" name="email" placeholder="email">
            <input type="submit" name="submit" value="Add User">
        </div>
    </form>

    <div>

    <a href="/login/orderlist?role=<?php echo $this->request->getQuery('role')?>">order list</a>
    <a href="/login/productlist?role=<?php echo $this->request->getQuery('role')?>">product list</a>
    <a href="/login/addproduct?role=<?php echo $this->request->getQuery('role')?>">add product</a>
    <a href="/login/addorder?role=<?php echo $this->request->getQuery('role')?>">addorder</a>
    <a href="/login/setting?role=<?php echo $this->request->getQuery('role')?>">update default</a>
    </div>
</body>

</html>