<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<h2>in login</h2>

<form action="" method="post">

<div>
    email
    <input type="text" name="email" placeholder="email">
</div>
<div>
    Password
    <input type="password" name="password" placeholder="password">
</div>
<div>
    <input type="submit" name="submit" value="Login">
</div>

</form>
    
</body>
</html>