<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<h2>default settings</h2>
<form action="" method="post">

price <input type="number" name="default_price">
<input type="submit" name="submit" value="update">

</form>
</body>
</html>